# Generated by Django 2.2.1 on 2020-04-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='creator',
            new_name='comid',
        ),
    ]
