# Generated by Django 2.2.1 on 2020-04-26 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Stories')),
            ],
        ),
    ]
