# Generated by Django 2.2.1 on 2020-04-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_characters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characters',
            old_name='title',
            new_name='name',
        ),
    ]
