# Generated by Django 2.2.1 on 2020-04-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200425_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='comid',
            new_name='comic',
        ),
    ]
