# Generated by Django 2.2.1 on 2020-04-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_characters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Characters',
        ),
    ]
