# Generated by Django 2.2.1 on 2020-04-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Characters',
        ),
    ]
