# Generated by Django 2.2.1 on 2020-04-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_users', 'Manage regular users.'), ('manage_staff', 'Manage staff.'), ('impersonate_users', 'Impersonate users.'))},
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default='https://res.cloudinary.com/mashafrancis/image/upload/v1552641620/kari4me/nan.jpg', max_length=1024),
        ),
    ]
